version: '3'

services:
  web:
    build:
      context: ./docker/web
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      # - FLASK_ENV=development
      - FLASK_ENV=production
    # depends_on:
    #   - db

  # db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'llm_image'
  #     MYSQL_ROOT_PASSWORD: 'llm_image'
  #   ports:
  #     - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

